const Courses = [
    {
        id:1,
        title:"BBA1",
        courseName:"COURSEA"
    },
    {
        id:2,
        title:"BBA2",
        courseName:"COURSEA"
    },
    {
        id:3,
        title:"BBA3",
        courseName:"COURSEA"
    },  
    {
        id:4,
        title:"BCA1",
        courseName:"COURSEB"
    },
    {
        id:5,
        title:"BCA2",
        courseName:"COURSEB"
    },
    {
        id:6,
        title:"BCA3",
        courseName:"COURSEB"
    },
    {
        id:7,
        title:"MBA1",
        courseName:"COURSEC"
    },
    {
        id:8,
        title:"MBA2",
        courseName:"COURSEC"
    },
    {
        id:9,
        title:"MBA3",
        courseName:"COURSEC"
    },
]
export default Courses